### PR TITLE
Enable Low Memory killer

### PR DESCRIPTION
**Pull request by rubencarneiro**
Enable Low Memory killer
Add missing IOSCHED features

### CODE REVIEW

**Review by dobey — CHANGES_REQUESTED** [review]
The diff shows `BT_HCIUART` and `TMPFS_POSIX_ACL` being changed from `y` to unset, but nothing related to low memory killer. So this seems wrong?

**Comment by rubencarneiro** [comment]
> The diff shows `BT_HCIUART` and `TMPFS_POSIX_ACL` being changed from `y` to unset, but nothing related to low memory killer. So this seems wrong?

No is correct. Just not declared on the pr

**Comment by dobey** [comment]
> No is correct. Just not declared on the pr

But the PR says "add missing IOSCHED features," and the only thing the diff does is apparently disable unrelated features? So how does disabling POSIX ACL on tmpfs, or Bluetooth HCI UART enable low memory killer or other IOSCHED features?

**Comment by rubencarneiro** [comment]
CONFIG_ANDROID_RAM_CONSOLE=y
CONFIG_ANDROID_RAM_CONSOLE=y
CONFIG_PERSISTENT_TRACER=y
CONFIG_PERSISTENT_TRACER=y
CONFIG_ANDROID_TIMED_GPIO=y
CONFIG_ANDROID_TIMED_GPIO=y
# CONFIG_ANDROID_LOW_MEMORY_KILLER is not set
CONFIG_ANDROID_LOW_MEMORY_KILLER=y
CONFIG_SPS=y
CONFIG_SPS=y
CONFIG_USB_BAM=y
CONFIG_USB_BAM=y
CONFIG_SPS_SUPPORT_BAMDMA=y
CONFIG_SPS_SUPPORT_BAMDMA=y
@@ -732,7 +732,12 @@ CONFIG_IP6_NF_QUEUE=y
CONFIG_IP6_NF_SECURITY=y
CONFIG_IP6_NF_SECURITY=y
CONFIG_IP6_NF_TARGET_HL=y
CONFIG_IP6_NF_TARGET_HL=y
CONFIG_DNS_RESOLVER=y
CONFIG_DNS_RESOLVER=y
CONFIG_IOSCHED_NOOP=y
CONFIG_IOSCHED_DEADLINE=y
CONFIG_IOSCHED_DEADLINE=y
CONFIG_IOSCHED_ROW=y
CONFIG_IOSCHED_CFQ=y
ONFIG_DEFAULT_NOOP=y
CONFIG_DEFAULT_IOSCHED="noop"
CONFIG_SUSPEND_TIME=y
CONFIG_SUSPEND_TIME=y
CONFIG_CONSOLE_TRANSLATIONS=y
CONFIG_CONSOLE_TRANSLATIONS=y
CONFIG_EVM=y
CONFIG_EVM=y

**Comment by rubencarneiro** [comment]
> > No is correct. Just not declared on the pr
> 
> But the PR says "add missing IOSCHED features," and the only thing the diff does is apparently disable unrelated features? So how does disabling POSIX ACL on tmpfs, or Bluetooth HCI UART enable low memory killer or other IOSCHED features?

I belive i changed that 

CONFIG_ANDROID_RAM_CONSOLE=y
CONFIG_ANDROID_RAM_CONSOLE=y
CONFIG_PERSISTENT_TRACER=y
CONFIG_PERSISTENT_TRACER=y
CONFIG_ANDROID_TIMED_GPIO=y
CONFIG_ANDROID_TIMED_GPIO=y
# CONFIG_ANDROID_LOW_MEMORY_KILLER is not set
CONFIG_ANDROID_LOW_MEMORY_KILLER=y
CONFIG_SPS=y
CONFIG_SPS=y
CONFIG_USB_BAM=y
CONFIG_USB_BAM=y
CONFIG_SPS_SUPPORT_BAMDMA=y
CONFIG_SPS_SUPPORT_BAMDMA=y
@@ -732,7 +732,12 @@ CONFIG_IP6_NF_QUEUE=y
CONFIG_IP6_NF_SECURITY=y
CONFIG_IP6_NF_SECURITY=y
CONFIG_IP6_NF_TARGET_HL=y
CONFIG_IP6_NF_TARGET_HL=y
CONFIG_DNS_RESOLVER=y
CONFIG_DNS_RESOLVER=y
CONFIG_IOSCHED_NOOP=y
CONFIG_IOSCHED_DEADLINE=y
CONFIG_IOSCHED_DEADLINE=y
CONFIG_IOSCHED_ROW=y
CONFIG_IOSCHED_CFQ=y
ONFIG_DEFAULT_NOOP=y
CONFIG_DEFAULT_IOSCHED="noop"
CONFIG_SUSPEND_TIME=y
CONFIG_SUSPEND_TIME=y
CONFIG_CONSOLE_TRANSLATIONS=y
CONFIG_CONSOLE_TRANSLATIONS=y
CONFIG_EVM=y
CONFIG_EVM=y

**Comment by rubencarneiro** [comment]
> > No is correct. Just not declared on the pr
> 
> But the PR says "add missing IOSCHED features," and the only thing the diff does is apparently disable unrelated features? So how does disabling POSIX ACL on tmpfs, or Bluetooth HCI UART enable low memory killer or other IOSCHED features?

Captura de ecrã de 2020-12-18 22-43-50

**Comment by rubencarneiro** [comment]
> > No is correct. Just not declared on the pr
> 
> But the PR says "add missing IOSCHED features," and the only thing the diff does is apparently disable unrelated features? So how does disabling POSIX ACL on tmpfs, or Bluetooth HCI UART enable low memory killer or other IOSCHED features?



Also fix camera stop working after opening morp browser by disable CONFIG_TMPFS_POSIX_ACL

**Pull request closed without merging**
