### PR TITLE
Remove CONFIG_TMPFS_POSIX_ACL as it breaks camera

### LINKED ISSUE #611: [xenial] Camera app image freeze
- Device: N5
- Channel: Xenial
- Build: 389

### Steps to reproduce
Just take a picture

### Expected behavior
no freeze

### Actual behavior
The image in the camera app freezes, blocking to take another picture.
Video more : as soon as i activate the video mode the image freeze, i cannot even start to record

### Logfiles and additional information
```

phablet@ubuntu-phablet:~$ tail -f .cache/upstart/application-legacy-camera-app-.log
file:///usr/share/camera-app//GalleryView.qml:70:5: QML OrientationHelper: All the parents must have an id.
State saving disabled for PhotogridView-photogridView:QQuickPinchArea-galleryViewPinch:_usr_share_camera-app__PhotogridView.qml:127:9:gridView, class OrientationHelper
file:///usr/share/camera-app//OptionsOverlay.qml:174:5: QML Information: Binding loop detected for property "height"
file:///usr/share/camera-app//OptionsOverlay.qml:174:5: QML Information: Binding loop detected for property "height"
[PERFORMANCE]: Last frame took 32 ms to render.
file:///usr/share/camera-app//ViewFinderExportConfirmation.qml:75:17: QML Item: Binding loop detected for property "height"
file:///usr/share/camera-app//ViewFinderExportConfirmation.qml:75:17: QML Item: Binding loop detected for property "height"
file:///usr/share/camera-app//ViewFinderExportConfirmation.qml:75:17: QML Item: Binding loop detected for property "height"
file:///usr/share/camera-app//OptionButton.qml:24:39: Unable to assign [undefined] to QString
file:///usr/share/camera-app//SlideshowView.qml:405: TypeError: Cannot read property 'actions' of null
	ext1: 1, ext2: 0 
	ext1: 0, ext2: 0 
	ext1: 0, ext2: 0 
qml: Picture saved as /home/phablet/Pictures/com.ubuntu.camera/image20180519_170459162.jpg
	ext1: 1, ext2: 0 
[PERFORMANCE]: Last frame took 36 ms to render.
[PERFORMANCE]: Last frame took 76 ms to render.
	ext1: 1, ext2: 0 
	ext1: 1, ext2: 0 
file:///usr/share/camera-app//OptionsOverlay.qml:174:5: QML Information: Binding loop detected for property "height"
file:///usr/share/camera-app//OptionsOverlay.qml:174:5: QML Information: Binding loop detected for property "height"
qml: Flipped
file:///usr/share/camera-app//OptionsOverlay.qml:174:5: QML Information: Binding loop detected for property "height"
file:///usr/share/camera-app//OptionsOverlay.qml:174:5: QML Information: Binding loop detected for property "height"
qml: Flipped
qml: optionsOverlayClose
[PERFORMANCE]: Last frame took 113 ms to render.
file:///usr/share/camera-app//OptionsOverlay.qml:174:5: QML Information: Binding loop detected for property "height"
file:///usr/share/camera-app//OptionsOverlay.qml:174:5: QML Information: Binding loop detected for property "height"
qml: Flipped
file:///usr/share/camera-app//OptionsOverlay.qml:174:5: QML Information: Binding loop detected for property "height"
file:///usr/share/camera-app//OptionsOverlay.qml:174:5: QML Information: Binding loop detected for property "height"
qml: Flipped
[PERFORMANCE]: Last frame took 36 ms to render.
Camera framerate boundaries are set by the backend
Camera framerate boundaries are set by the backend
QObject::connect: No such slot AalImageCaptureControl::onPreviewReady()
Camera framerate boundaries are set by the backend
Camera framerate boundaries are set by the backend
Already have a texture id and video sink, not creating a new one
	ext1: 0, ext2: 0 
	ext1: 0, ext2: 0 
qml: Picture saved as /home/phablet/Pictures/com.ubuntu.camera/image20180519_170638328.jpg
Camera framerate boundaries are set by the backend
Camera framerate boundaries are set by the backend
```

### PR DESCRIPTION
**Pull request by mariogrip**
I have absolutely no clue why this works ヽ༼ ツ ༽ﾉ ︵┻━┻
but I if I would guess it has something to do with permissions?

Fixes: https://github.com/ubports/ubuntu-touch/issues/611
Change-Id: I755715492910e6bb9d2db6a79737a6d09dc57903

### CODE REVIEW

**Comment by NeoTheThird** [comment]
waat

**Comment by NeoTheThird** [comment]
maybe put a comment in the file about that?

**Comment by mariogrip** [comment]
> maybe put a comment in the file about that?

Like that? (see new commit)

**Comment by UniversalSuperBox** [comment]
If Anbox still works with this change... I guess it's okay to merge.

Hopefully newer devices save us from this nonsense.

**Comment by Flohack74** [comment]
This kernel option also gave me a headache one day, seems its a bunch of incorrectly picked commits inside the Android kernel or idk

**Review by Flohack74 — APPROVED** [review]

**Review by peat-psuwit — CHANGES_REQUESTED** [review]
Please test video playback. This config allows logind (or something) to give necessary permission to `/dev/video*` device nodes required for HW accelerated video decoding. Please see not only if the video plays but also if it's using HW decoder (possibly by looking at CPU usage).

**Comment by mariogrip** [comment]
> Please test video playback. This config allows logind (or something) to give necessary permission to `/dev/video*` device nodes required for HW accelerated video decoding. Please see not only if the video plays but also if it's using HW decoder (possibly by looking at CPU usage).

Please note this config got added for anbox and was not added by android. but it seems to be fine from my tests.

**Comment by mariogrip** [comment]
> If Anbox still works with this change... I guess it's okay to merge.
> 
> Hopefully newer devices save us from this nonsense.

anbox works

**Comment by Flohack74** [comment]
@peat-psuwit I suggest we let this pass into devel to get wider feedback.

**Review by peat-psuwit — APPROVED** [review]
Hmm, video decoding on this device doesn't require this config? Then I'll follow @Flohack74 suggestion and let this go to testing. However, may I see the output of `ls -lh /dev/video*` from this device?

Also, I think running this config through `make oldconfig` might cleanup things a bit.

**Pull request merged**
